builds:
-
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - freebsd
    - openbsd
    - windows
archives:
- format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
  prerelease: auto
dockers:
  -
    binaries:
    - sampleapp
    image_templates:
    - "docker.pkg.github.com/pellared/sampleapp/sampleapp:latest"
    - "docker.pkg.github.com/pellared/sampleapp/sampleapp:{{ .Major }}"
    - "docker.pkg.github.com/pellared/sampleapp/sampleapp:{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/pellared/sampleapp/sampleapp:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
